%yaml
# Databricks Environment Configuration

# Logging Configuration for Job Execution
logging:
  log_path: "dbfs:/logs/job_execution"
  log_level: "INFO"
  enable_audit_logs: true
  enable_metrics: true
  metrics_path: "dbfs:/metrics/job_execution"